### ISSUE TITLE
When switching between servers invalid taskIds cause permanent explosions

### ISSUE THREAD

**Issue by accolasia** [openmastery/ideaflow#21]
If any batch contains an invalid taskId, no data will be able to be sent to the server, forever more, because the server explodes with a NPE and the client will retry every 30s indefinitely.

config.JerseyConfig] in context with path [] threw exception [java.lang.NullPointerException: Cannot set property 'modifyDate' on null object] with root cause

java.lang.NullPointerException: Cannot set property 'modifyDate' on null object
        at org.codehaus.groovy.runtime.NullObject.setProperty(NullObject.java:77)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:192)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:482)
        at org.openmastery.publisher.core.IFMBatchService$_saveTaskModifyDates_closure3.doCall(IFMBatchService.groovy:86)

**Comment by mlueders** [comment]
This has been fixed on the plugin side - batch files now contain just one task and batches are skipped and retried later if an error occurs.
